// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Body1: typeof import('./components/Body-1.vue')['default']
    Body10: typeof import('./components/Body-10.vue')['default']
    Body2: typeof import('./components/Body-2.vue')['default']
    Body3: typeof import('./components/Body-3.vue')['default']
    Body4: typeof import('./components/Body-4.vue')['default']
    Body5: typeof import('./components/Body-5.vue')['default']
    Body6: typeof import('./components/Body-6.vue')['default']
    Body7: typeof import('./components/Body-7.vue')['default']
    Body8: typeof import('./components/Body-8.vue')['default']
    Body9: typeof import('./components/Body-9.vue')['default']
    Companies: typeof import('./components/Companies.vue')['default']
    Copyright: typeof import('./components/Copyright.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GettingStarted: typeof import('./components/GettingStarted.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Security: typeof import('./components/Security.vue')['default']
  }
}
